### ISSUE TITLE
npm install --save teaset

### ISSUE THREAD

**Issue by yangliyang5544** [rilyu/teaset#147]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\DevelopTools\\node8.9.3\\node.exe',
1 verbose cli   'C:\\Users\\YangLiyang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'teaset' ]
2 info using npm@5.3.0
3 info using node@v8.9.3
4 verbose npm-session 56f059e57c6ef70b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npm.taobao.org/teaset 246ms (from cache)
8 silly pacote range manifest for teaset@^0.4.9 fetched in 339ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule teaset@0.4.9 checking installable status
14 http fetch GET 304 https://registry.npm.taobao.org/prop-types 176ms (from cache)
15 silly pacote range manifest for prop-types@^15.5.10 fetched in 180ms
16 silly resolveWithNewModule prop-types@15.6.0 checking installable status
17 silly fetchPackageMetaData error for react-native-deprecated-custom-components@github:facebookarchive/react-native-custom-components Command failed: C:\Program Files\Git\bin\git.EXE submodule update -q --init --recursive
17 silly fetchPackageMetaData git: 'submodule' is not a git command. See 'git --help'.
18 verbose stack Error: Command failed: C:\Program Files\Git\bin\git.EXE submodule update -q --init --recursive
18 verbose stack git: 'submodule' is not a git command. See 'git --help'.
18 verbose stack
18 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
18 verbose stack     at emitTwo (events.js:126:13)
18 verbose stack     at ChildProcess.emit (events.js:214:7)
18 verbose stack     at maybeClose (internal/child_process.js:925:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19 verbose cwd E:\Code\RN_Code\xx
20 verbose Windows_NT 10.0.14393
21 verbose argv "E:\\DevelopTools\\node8.9.3\\node.exe" "C:\\Users\\YangLiyang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "teaset"
22 verbose node v8.9.3
23 verbose npm  v5.3.0
24 error code 1
25 error Command failed: C:\Program Files\Git\bin\git.EXE submodule update -q --init --recursive
25 error git: 'submodule' is not a git command. See 'git --help'.
26 verbose exit [ 1, true ]

**Comment by yangliyang5544** [comment]
几天前安装的时候还是正常的

**Comment by yangliyang5544** [comment]
为啥 git submodule update 不可以工作
