### ISSUE TITLE
android  release 包无法运行

### ISSUE THREAD

**Issue by MissBears** [rilyu/teaset#75]
FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.example, PID: 27120
                                                   com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'i.View.propTypes.style'), stack:
                                                   <unknown>@318:4103
                                                   i@2:565
                                                   n@2:348
                                                   t@2:210
                                                   <unknown>@316:197
                                                   i@2:565
                                                   n@2:348
                                                   t@2:210
                                                   <unknown>@315:147
                                                   i@2:565
                                                   n@2:348
                                                   t@2:210
                                                   <unknown>@314:246
                                                   i@2:565
                                                   n@2:348
                                                   t@2:210
                                                   <unknown>@303:288
                                                   i@2:565
                                                   n@2:348
                                                   t@2:210
                                                   <unknown>@302:140
                                                   i@2:565
                                                   n@2:348
                                                   t@2:210
                                                   <unknown>@12:38
                                                   i@2:565
                                                   n@2:278
                                                   t@2:210
                                                   global code@467:9
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
                                                       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                       at java.lang.Thread.run(Thread.java:762)

**Comment by rilyu** [comment]
你的 rn 版本是多少？View.propTypes.style 在 Teaset 里大量使用，View.propTypes 在很久以前就有的了

**Comment by asmh1989** [comment]
0.49 后已经不支持在release 下使用 View.propTypes,  要用 ViewPropTypes 替代

**Comment by kule123** [comment]
那什么时候能支持到最新版啊

**Comment by rilyu** [comment]
我开发环境用的就是 0.49.2 ，在 dev 环境下都测试了双平台，但 release 确实报错了，看 View 的源代码确实是只能在 dev 环境下使用 View.propTypes ，稍后我做一下升级

**Comment by rilyu** [comment]
已修正：https://github.com/rilyu/teaset/commit/76ecccb93191b9a4c8937b5661ef60beadc7a0aa

**Comment by kule123** [comment]
多谢 多谢
